---
- name: Create a text file on client servers
  hosts: all
  become: yes

  tasks:
    - name: Create a file in /tmp
      file:
        path: /tmp/ansible_test.txt
        state: touch
        mode: '0644'

    - name: Add content to the file
      lineinfile:
        path: /tmp/ansible_test.txt
        line: "This file was created by Ansible on {{ inventory_hostname }}"
        create: yes
